/* # Task 1: Data Ingestion
Load the raw data from all source tables (SensorDataRaw, WeatherDataRaw, 
SoilDataRaw, CropDataRaw, PestDataRaw, IrrigationDataRaw, LocationDataRaw) 
into staging tables within the Data Warehouse Schema.
*/

/* STEP 1 - LOAD TABLE FROM RAW DATA TO DATAORBIQ STAGE SCHEMA */
CREATE TABLE DFA23RAWDATA.DATAORBIQ.STAGE_LOCATIONRAWDATA CLONE DFA23RAWDATA.RAWDATA.LOCATIONDATARAW;
CREATE TABLE DFA23RAWDATA.DATAORBIQ.STAGE_IRRIGATIONRAWDATA CLONE DFA23RAWDATA.RAWDATA.IRRIGATIONDATARAW;
CREATE TABLE DFA23RAWDATA.DATAORBIQ.STAGE_CROPRAWDATA CLONE DFA23RAWDATA.RAWDATA.CROPDATARAW;
CREATE TABLE DFA23RAWDATA.DATAORBIQ.STAGE_PESTRAWDATA CLONE DFA23RAWDATA.RAWDATA.PESTDATARAW;
CREATE TABLE DFA23RAWDATA.DATAORBIQ.STAGE_SENSORRAWDATA CLONE DFA23RAWDATA.RAWDATA.SENSORDATARAW;
CREATE TABLE DFA23RAWDATA.DATAORBIQ.STAGE_SOILRAWDATA CLONE DFA23RAWDATA.RAWDATA.SOILDATARAW;
CREATE TABLE DFA23RAWDATA.DATAORBIQ.STAGE_WEATHERRAWDATA CLONE DFA23RAWDATA.RAWDATA.WEATHERDATARAW;

/* STEP 2 - CREATE STAGE TABLE IN POSTGRESQL */
create table locationdataraw (
	SENSOR_ID VARCHAR(30),
	LOCATION_NAME VARCHAR(150),
	LATITUDE VARCHAR(100),
	LONGITUDE VARCHAR(100),
	ELEVATION VARCHAR(100),
	REGION VARCHAR(100)
);
create table irrigationdataraw (
	SENSOR_ID VARCHAR(1000),
	TIMESTAMP VARCHAR(1000),
	IRRIGATION_METHOD VARCHAR(1000),
	WATER_SOURCE VARCHAR(1000),
	IRRIGATION_DURATION_MIN VARCHAR(1000)
);
create table cropdataraw (
	TIMESTAMP VARCHAR(1000),
	CROP_TYPE VARCHAR(1000),
	CROP_YIELD VARCHAR(1000),
	GROWTH_STAGE VARCHAR(1000),
	PEST_ISSUE VARCHAR(1000)
);
create table pestdataraw (
	TIMESTAMP VARCHAR(1000),
	PEST_TYPE VARCHAR(1000),
	PEST_DESCRIPTION VARCHAR(1000),
	PEST_SEVERITY VARCHAR(1000)
);
create table sensordataraw (
	SENSOR_ID VARCHAR(1000),
	TIMESTAMP VARCHAR(1000),
	TEMPERATURE VARCHAR(1000),
	HUMIDITY VARCHAR(1000),
	SOIL_MOISTURE VARCHAR(1000),
	LIGHT_INTENSITY VARCHAR(1000),
	BATTERY_LEVEL VARCHAR(1000)
);
create table soildataraw (
	TIMESTAMP VARCHAR(1000),
	SOIL_COMP VARCHAR(1000),
	SOIL_MOISTURE VARCHAR(1000),
	SOIL_PH VARCHAR(1000),
	NITROGEN_LEVEL VARCHAR(1000),
	PHOSPHORUS_LEVEL VARCHAR(1000),
	ORGANIC_MATTER VARCHAR(1000)
);
create table weatherdataraw (
	TIMESTAMP VARCHAR(1000),
	WEATHER_CONDITION VARCHAR(1000),
	WIND_SPEED VARCHAR(1000),
	PRECIPITATION VARCHAR(1000)
);

/* STEP 3 - COPY FILE TO TABLE */
COPY locationdataraw
FROM 'C:\Users\Hp\Downloads\LOCATIONDATARAW.csv'
DELIMITER ','
CSV HEADER;

COPY irrigationdataraw
FROM 'C:\Users\Hp\Downloads\irrigationdataraw.csv'
DELIMITER ','
CSV HEADER;

COPY cropdataraw
FROM 'C:\Users\Hp\Downloads\cropdataraw.csv'
DELIMITER ','
CSV HEADER;

COPY pestdataraw
FROM 'C:\Users\Hp\Downloads\pestdataraw.csv'
DELIMITER ','
CSV HEADER;

COPY sensordataraw
FROM 'C:\Users\Hp\Downloads\sensordataraw.csv'
DELIMITER ','
CSV HEADER;

COPY soildataraw
FROM 'C:\Users\Hp\Downloads\soildataraw.csv'
DELIMITER ','
CSV HEADER;

COPY weatherdataraw
FROM 'C:\Users\Hp\Downloads\weatherdataraw.csv'
DELIMITER ','
CSV HEADER;