/* CREATE STAGE TABLES */
CREATE TABLE DFA23RAWDATA.DATAORBIQ.STAGE_LOCATIONDATA (
    sensorid VARCHAR (20),
    locationname VARCHAR (30),
    latitude DECIMAL(8, 6),
    longitude DECIMAL(9, 6),
    elevation DECIMAL(8, 2),
    region VARCHAR (20)
);
CREATE TABLE DFA23RAWDATA.DATAORBIQ.STAGE_IRRIGATIONDATA (
    sensorid VARCHAR (20),
	timestamp TIMESTAMP,
	irrigationmethod VARCHAR(20),
	watersource VARCHAR(20),
	irrigationdurationmin INTEGER
);
CREATE TABLE DFA23RAWDATA.DATAORBIQ.STAGE_CROPDATA (
	timestamp TIMESTAMP,
	croptype VARCHAR(20),
	cropyield DECIMAL(8, 2),
	growthstage VARCHAR(50),
	pestissue VARCHAR(100)
);
CREATE TABLE DFA23RAWDATA.DATAORBIQ.STAGE_PESTDATA (
	timestamp TIMESTAMP,
	pesttype VARCHAR(20),
	pestdescription TEXT,
	pestseverity VARCHAR(20)
);
CREATE TABLE DFA23RAWDATA.DATAORBIQ.STAGE_SOILDATA (
	timestamp TIMESTAMP,
	soilcomp DECIMAL(5, 2),
	soilmoisture DECIMAL(5, 2),
	soilph DECIMAL(4, 2),
	nitrogenlevel DECIMAL(5, 2),
	phosphoruslevel DECIMAL(5, 2),
	organicmatter DECIMAL(5, 2)
);
CREATE TABLE DFA23RAWDATA.DATAORBIQ.STAGE_WEATHERDATA (
	timestamp TIMESTAMP,
	weathercondition VARCHAR(50),
	windspeed DECIMAL(5, 2),
	precipitation DECIMAL(5, 2)
);
CREATE TABLE DFA23RAWDATA.DATAORBIQ.STAGE_SENSORDATA (
    sensorid VARCHAR (10),
	timestamp TIMESTAMP,
	temperaturef DECIMAL(5, 2),
	humidity DECIMAL(5, 2),
	soilmoisture DECIMAL(5, 2),
	lightintensity DECIMAL(8, 2),
	batterylevel DECIMAL(8, 2)
);

/* ALTER COLUMN NAME */
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_LOCATIONRAWDATA RENAME COLUMN Sensor_Id TO sensorid;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_LOCATIONRAWDATA RENAME COLUMN Location_Name TO locationname;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_IRRIGATIONRAWDATA RENAME COLUMN Sensor_Id TO sensorid;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_IRRIGATIONRAWDATA RENAME COLUMN Irrigation_Method TO irrigationmethod;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_IRRIGATIONRAWDATA RENAME COLUMN Water_Source TO watersource;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_IRRIGATIONRAWDATA RENAME COLUMN Irrigation_Duration_Min TO irrigationdurationmin;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_CROPRAWDATA RENAME COLUMN Crop_Type TO croptype;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_CROPRAWDATA RENAME COLUMN Crop_Yield TO cropyield;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_CROPRAWDATA RENAME COLUMN Growth_Stage TO growthstage;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_CROPRAWDATA RENAME COLUMN Pest_Issue TO pestissue;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_PESTRAWDATA RENAME COLUMN Pest_Type TO pesttype;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_PESTRAWDATA RENAME COLUMN Pest_Description TO pestdescription;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_PESTRAWDATA RENAME COLUMN Pest_Severity TO pestseverity;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_SOILRAWDATA RENAME COLUMN Soil_Comp TO soilcomp;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_SOILRAWDATA RENAME COLUMN Soil_Moisture TO soilmoisture;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_SOILRAWDATA RENAME COLUMN Soil_PH TO soilph;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_SOILRAWDATA RENAME COLUMN Nitrogen_Level TO nitrogenlevel;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_SOILRAWDATA RENAME COLUMN Phosphorus_Level TO phosphoruslevel;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_SOILRAWDATA RENAME COLUMN Organic_Matter TO organicmatter;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_WEATHERRAWDATA RENAME COLUMN Weather_Condition TO weathercondition;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_WEATHERRAWDATA RENAME COLUMN Wind_Speed TO windspeed;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_SENSORRAWDATA RENAME COLUMN Sensor_Id TO sensorid;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_SENSORRAWDATA RENAME COLUMN Temperature TO temperaturef;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_SENSORRAWDATA RENAME COLUMN Soil_Moisture TO soilmoisture;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_SENSORRAWDATA RENAME COLUMN Light_Intensity TO lightintensity;
ALTER TABLE DFA23RAWDATA.DATAORBIQ.STAGE_SENSORRAWDATA RENAME COLUMN Battery_Level TO batterylevel;

/* INSERT INTO STAGE RAW DATA FROM IMPORTED RAW DATA
The table being imported into have the right type and column name.
This table now serve as raw data to create dimension tables */
 */
INSERT INTO DFA23RAWDATA.DATAORBIQ.STAGE_LOCATIONDATA SELECT sensorid, locationname,
    latitude::DECIMAL(8, 6), longitude::DECIMAL(9, 6), elevation::DECIMAL(8, 2), region FROM DFA23RAWDATA.DATAORBIQ.STAGE_LOCATIONRAWDATA;

INSERT INTO DFA23RAWDATA.DATAORBIQ.STAGE_IRRIGATIONDATA SELECT sensorid, TIMESTAMP::TIMESTAMP, 
    irrigationmethod, watersource, irrigationdurationmin::INTEGER FROM DFA23RAWDATA.DATAORBIQ.STAGE_IRRIGATIONRAWDATA;

INSERT INTO stage_croprawdata SELECT Timestamp::TIMESTAMP, croptype, 
    cropyield::DECIMAL(8, 2), growthstage, pestissue FROM croprawdata;

INSERT INTO stage_pestrawdata SELECT Timestamp::TIMESTAMP, pesttype, 
    pestdescription, pestseverity FROM pestrawdata;

INSERT INTO stage_soilrawdata SELECT Timestamp::TIMESTAMP, soilcomp::DECIMAL(5, 2), 
    soilmoisture::DECIMAL(5, 2), soilph::DECIMAL(4, 2), nitrogenlevel::DECIMAL(5, 2), phosphoruslevel::DECIMAL(5, 2), organicmatter::DECIMAL(5, 2) FROM soilrawdata;

INSERT INTO stage_weatherrawdata SELECT Timestamp::TIMESTAMP, weathercondition, 
    windspeed::DECIMAL(5, 2), precipitation::DECIMAL(5, 2) FROM weatherrawdata;

INSERT INTO DFA23RAWDATA.DATAORBIQ.STAGE_SENSORDATA SELECT sensorid, Timestamp::TIMESTAMP, 
     temperaturef::DECIMAL(5, 2), humidity::DECIMAL(5, 2), soilmoisture::DECIMAL(5, 2), lightintensity::DECIMAL(8, 2), batterylevel::DECIMAL(8, 2) FROM DFA23RAWDATA.DATAORBIQ.STAGE_SENSORRAWDATA;

